# Generated by Django 4.1.7 on 2023-03-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='ФИО', max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(help_text='+7 999 99 99 999', max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Email', max_length=50, verbose_name='Email')),
                ('landing_page', models.BooleanField(default=False, help_text='Лендинг', verbose_name='Лендинг')),
                ('business_card_website', models.BooleanField(default=False, help_text='Сайт-визитка', verbose_name='Сайт-визитка')),
                ('corporate_website', models.BooleanField(default=False, help_text='Корпоративный сайт', verbose_name='Корпоративный сайт')),
                ('whim', models.BooleanField(default=False, help_text='Каприз', verbose_name='Каприз')),
                ('less_than_five_hundred_thousand', models.BooleanField(default=False, help_text='Менее 500 Т', verbose_name='Менее 500 Т/Р')),
                ('less_than_million', models.BooleanField(default=False, help_text='Менее Мил', verbose_name='Менее Мил')),
                ('more_than_million', models.BooleanField(default=False, help_text='Более Мил', verbose_name='Более Мил')),
                ('arbitrary_option', models.BooleanField(default=False, help_text='Не знаю', verbose_name='Не знаю')),
                ('about_project', models.TextField(help_text='Опишите Задачу', verbose_name='О проекте')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
